### PR TITLE
package.json fixes

### PR DESCRIPTION
**Pull request by shime**

### CODE REVIEW

**Comment by rumkin** [comment]
What's the goal of changes?

**Comment by shime** [comment]
- I'm not going to explain `main`. 
- Adding `lib` to `directories` basically just gives info about where to find the source for your package ([more info here](https://docs.npmjs.com/files/package.json#directorieslib)). 
- `files` specifies which files are included when your package is installed, so you don't include unnecessary test or example files.

**Comment by rumkin** [comment]
I'd prefer to see package code in build directory, src is for development.

**Comment by shime** [comment]
What are you referring to? You only have `src` folder in your package, so it's okay. It would make sense to have a `build` directory if there was a build step required.

**Comment by rumkin** [comment]
Yep, build step is not required for one file. But this is semantic layout and my dev tools is configured for this. Is it a big issue for you?

**Comment by shime** [comment]
I'm not following. What changes are needed for this to be merged? Could you be more specific?

**Comment by rumkin** [comment]
- `files` option should contain build, readme.md and license.
- `main` should remain build/emoji-favicon.js

**Comment by shime** [comment]
I have a problem with that since `build` is not a directory and if we point `main` to inexistent file it will break your package, which is happening now when you try to install it with `npm install --save rumkin/emoji-favicon` and `require('emoji-favicon')`.

**Comment by rumkin** [comment]
It's strange because I have `prepublish` script in `package.json` which run `build` and successfully published and install current version.

**Comment by shime** [comment]
Ah got it now. Well, with your current setup it's not possible to install this package from Github. Via `npm install rumkin/emoji-favicon`. That's what's breaking things for me and the current NPM version is still broken, so please update that.

**Comment by rumkin** [comment]
Thanks 👍

**Pull request merged**
